import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="navhedar">
                <nav>
                   <div className='navlogo'>
                        <h1>Mr.<span>Pie</span></h1>
                   </div>
                   <div className="navItem">
                        <ul>
                          <li>
                            <Link className="navLink" href={'/'}>Home</Link>
                          </li>
                          <li>
                            <Link className="navLink" href={'#about'}>About</Link>
                          </li>
                          <li>
                            <Link className="navLink" href={'#service'}>Service</Link>
                          </li>
                          <li>
                            <Link className="navLink" href={'#portfolio'}>Portfolio</Link>
                          </li>
                          <li>
                            <Link className="navLink" href={'#contact'}>Contact</Link>
                          </li>
                        </ul>
                   </div>
                </nav>
        </header>

        <main>
              {children}
        </main>

        <footer>
                <div className="leftFot">
                      <p> <span style={{fontSize:'1.5rem'}}>&copy;</span>Copyright By Mr.Pie .All right reserve 2024</p>
                </div>
                <div className="midFot">
                     <Link style={{color:'white',textDecoration:'none'}} href='https://www.facebook.com/Mr.1Pie/'>Facebook</Link><span>|</span>
                     <Link style={{color:'white',textDecoration:'none'}} href='https://x.com/MrPieX'>X</Link><span>|</span>
                     <Link style={{color:'white',textDecoration:'none'}} href='https://www.youtube.com/@Mr.1Pie'>YouTube</Link><span>|</span>
                     <Link style={{color:'white',textDecoration:'none'}} href='https://www.linkedin.com/in/heyAbdullahBro'>LinkedIn</Link>
                </div>
                <div className="rightFot" style={{rotate:'-90deg'}}>
                  <Link href='/' style={{backgroundColor:"green",color:'white',textDecoration:'none',fontSize:'2rem',borderRadius:'50%'}}>{'->'}</Link>
                </div>
        </footer>
      </body>
    </html>
  );
}
